staging: true
staging_words:
- enum gw1.actor.class:014
- enum gw1.actuation.authority:000
- enum gw1.service.mode:000
- enum i2c.adc.channel
- enum i2c.adc.type:000
- type gw.adc.waveform:000
- type i2c.multichannel.dt.relay.component.gt:004
- type i2c.thermistor.channel.config:000
- type i2c.thermistor.reader.component.gt:000
- type layout.lite:013
- type pico.flow.module.component.gt:001
- type pico.tank.module.component.gt:012
- type relay.actor.config:003
- type sim.pico.tank.module.component.gt:001
- type spaceheat.node.gt:303
