staging: true
staging_words:
- enum i2c.adc.channel
- type gw.channel.jump.stats:000
- type gw.experiment.run:000
- type i2c.thermistor.channel.config:001
- type i2c.thermistor.channel.config:002
- type i2c.thermistor.reader.component.gt:001
- type i2c.thermistor.reader.component.gt:002
- type i2c.thermistor.reader.component.gt:003
